### ISSUE TITLE
User role body class

### ISSUE THREAD

**Issue by ChippyWhips** [wp-kit/foundation#2]
I found this function for outputting the user roles into body class, can we have something like this added in by default please? This goes hand in hand with my previous pull request to hide var_dumps from non admin/dev users

```
if ( is_user_logged_in() ) {
    add_filter('body_class','add_role_to_body');
    add_filter('admin_body_class','add_role_to_body');
}
function add_role_to_body($classes) {
    $current_user = new WP_User(get_current_user_id());
    $user_role = array_shift($current_user->roles);
    if (is_admin()) {
        $classes .= 'role-'. $user_role;
    } else {
        $classes[] = 'role-'. $user_role;
    }
    return $classes;
}
```

**Comment by terence1990** [comment]
This isn't something everyone would want, and besides WP Kit Core is used for Theme, Plugin and Standalone version so it cannot assume a theme is active, this Issue should be added WP Kit repo where it could be added to the default AppController
