### ISSUE TITLE
More control over register post type labels

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/foundation#3]
Hello,

I really could do with greater control of these labels, are you able to make them all overridable please.

Thanks

	register_post_type( $this->slug , array(
		'labels'             => array(
			'name'               => _x( $plural, 'post type general name', 'wpkit' ),
			'singular_name'      => _x( $name, 'post type singular name', 'wpkit' ),
			'menu_name'          => _x( $this->menu_name ? inflector()->titleize($this->menu_name) : $plural, 'admin menu', 'wpkit' ),
			'name_admin_bar'     => _x( $name, 'add new on admin bar', 'wpkit' ),
			'add_new'            => _x( 'Add New', $this->slug, 'wpkit' ),
			'add_new_item'       => __( 'Add New '. $name, 'wpkit' ),
			'new_item'           => __( 'New ' . $name, 'wpkit' ),
			'edit_item'          => __( 'Edit ' . $name, 'wpkit' ),
			'view_item'          => __( 'View ' . $name, 'wpkit' ),
			'all_items'          => __( $this->all_items ? inflector()->titleize( $this->all_items ) : 'All '. $plural, 'wpkit' ),
			'search_items'       => __( 'Search ' . $plural, 'wpkit' ),
			'parent_item_colon'  => __( 'Parent ' . $plural . ':', 'wpkit' ),
			'not_found'          => __( 'No ' . strtolower($plural) . ' found.', 'wpkit' ),
			'not_found_in_trash' => __( 'No ' . strtolower($plural) . ' found in Trash.', 'wpkit' )
		),

**Comment by terence1990** [comment]
@matt3224 you can now do this as of version ```1.5.7```

Please see below commit to see how you can apply labels

https://github.com/wp-kit/core/commit/60b7e2524721d2f135e78fcb1cd4a6aa61a2cabd
