### ISSUE TITLE
Partial menu tree selection for TimberMenu

### ISSUE THREAD

**Issue by mattpilott** [wp-kit/foundation#4]
Hello,

I really could do with this nifty little addition as I keep running into needing it.
```php
the_component( 'App', 'sub-menu', [
    'menu' => new TimberMenu('header-menu'),
    'theme_dir' => THEME_URI
]);
```
Take that example, this is the current usage in wp-kit. Now can we add an option to fetch the children of a link in the menu.
```php
the_component( 'App', 'sub-menu', [
    'menu' => new TimberMenu('header-menu'),
    'submenu' => 'Products', // Of course this could be either a title, slug, id or permalink whichever is easiest for you to implement.
    'theme_dir' => THEME_URI // Also is this needed?
]);
```
Thanks

**Comment by mattpilott** [comment]
Here's what i need to do in twig atm which is fine but also not amazing, i guess its more timberMenu that needs this stuff really. Unless you know a good way?

```twig
{% for item in menu.get_items %}

    {% if submenu and item.title == submenu %}

        {% for child in item.get_children %}

            <a class="subnav__link  {{child.classes | join(' ')}}" href="{{child.get_link}}">{{ child.title }}</a>

        {% endfor %}

    {% endif %}

{% endfor %}
```

**Comment by terence1990** [comment]
@matt3224 this is the correct way, unfortunately there is no way to just get the child items in TimberMenu like this.

You could look into ```wp_get_nav_menu_items``` function

https://developer.wordpress.org/reference/functions/wp_get_nav_menu_items/
